#!/usr/bin/env python3
"""
Convert Raindance.png (257x257 16-bit grayscale) to a baked C++ header
RAINDANCE_HEIGHTS[257][257] consumed by program/code/wasm_main.cpp.

Source: levizoesch/tribes.mapping (MIT). 16-bit grayscale, raw [0..65535].

Vertical scale: the canonical Raindance.ted (Tribes 1 v1.11) GBLK header
encodes range = [6.6539, 76.899] meters in IEEE-754 floats at byte offsets
0xc8..0xd0 of the file. The community PNG normalizes that range to the full
uint16 dynamic range [0..65535], so we restore the canonical range here:

    height_m = VERT_MIN + (raw / 65535) * (VERT_MAX - VERT_MIN)

This matches Sierra/Dynamix's Raindance terrain bit-perfectly *to the
resolution of the community PNG* (which is 257x257, the same as the .ted's
GBLK block_size). The only fidelity loss vs. extracting from the .ted
directly is whatever LZH-decompression rounding the original UE5 export
introduced. The R32.0.2 task tracked in the brief is to write a real
LZH-aware .ted parser and re-bake from the binary directly.
"""
import sys
from pathlib import Path
from PIL import Image
import numpy as np

HERE = Path(__file__).parent
SRC = HERE / "heightmap.png"
DST_HEADER = HERE.parent.parent.parent / "program" / "code" / "raindance_heightmap.h"

GRID_N = 257
STEP_M = 8.0          # 8m per cell (Tribes 1 native)
# Canonical range from Raindance.ted GBLK header (verified by xxd)
VERT_MIN = 6.6539     # raw=0     -> 6.65m
VERT_MAX = 76.899     # raw=65535 -> 76.90m

img = Image.open(SRC)
assert img.size == (GRID_N, GRID_N), f"expected {GRID_N}x{GRID_N}, got {img.size}"
assert img.mode in ("I;16", "I"), f"expected 16-bit grayscale, got {img.mode}"

raw = np.array(img, dtype=np.float32)
heights_m = VERT_MIN + (raw / 65535.0) * (VERT_MAX - VERT_MIN)
hmin = float(heights_m.min())
hmax = float(heights_m.max())
hmean = float(heights_m.mean())

print(f"loaded {SRC.name}: {raw.shape}, raw [{int(raw.min())}..{int(raw.max())}]")
print(f"heights_m: min={hmin:.3f} max={hmax:.3f} mean={hmean:.3f}")
print(f"world: {GRID_N - 1} * {STEP_M}m = {(GRID_N - 1) * STEP_M:.0f}m square")
print(f"writing header to {DST_HEADER}")

lines = []
lines.append("#ifndef RAINDANCE_HEIGHTMAP_H")
lines.append("#define RAINDANCE_HEIGHTMAP_H")
lines.append("")
lines.append("// Generated by assets/maps/raindance/build_heightmap.py")
lines.append("// Source: levizoesch/tribes.mapping (MIT) Raindance.png 257x257 16-bit grayscale")
lines.append(f"// Vertical scale: raw uint16 [0..65535] -> [{VERT_MIN:.4f}..{VERT_MAX:.4f}]m")
lines.append(f"// Range source: Raindance.ted GBLK header (canonical Sierra/Dynamix v1.11)")
lines.append("// Native Tribes 1 grid: 256+1 vertices, 8m spacing, 2048m square")
lines.append("")
lines.append(f"static const int RAINDANCE_SIZE = {GRID_N}; // 256+1")
lines.append(f"static const float RAINDANCE_HEIGHT_MIN = {hmin:.6f}f;")
lines.append(f"static const float RAINDANCE_HEIGHT_MAX = {hmax:.6f}f;")
lines.append("")
lines.append(f"static const float RAINDANCE_HEIGHTS[{GRID_N}][{GRID_N}] = {{")
for z in range(GRID_N):
    row_vals = ", ".join(f"{heights_m[z, x]:.4f}f" for x in range(GRID_N))
    comma = "," if z < GRID_N - 1 else ""
    lines.append(f"    {{{row_vals}}}{comma}")
lines.append("};")
lines.append("")
lines.append("#endif // RAINDANCE_HEIGHTMAP_H")

DST_HEADER.write_text("\n".join(lines))
sz = DST_HEADER.stat().st_size
print(f"wrote {DST_HEADER} ({sz} bytes, {sz/1024:.1f} KB)")
