#!/usr/bin/env python3
"""
Convert Raindance.png (257x257 16-bit grayscale) to a baked C++ header
RAINDANCE_HEIGHTS[257][257] consumed by program/code/wasm_main.cpp.

Source: levizoesch/tribes.mapping (MIT). 16-bit grayscale, raw [0..65535].

Vertical scale: VERT_SCALE_M is the height of pure-white pixels in meters.
Tribes 1 Raindance native vertical relief is approximately 200m. Per the upstream
README the recommended UE5 heightScale is 70 (UE5 unit ~ 1cm => ~200m relief).

Tunable. After R32.0 ships, A/B against the reference video and adjust.
"""
import sys
from pathlib import Path
from PIL import Image
import numpy as np

HERE = Path(__file__).parent
SRC = HERE / "heightmap.png"
DST_HEADER = HERE.parent.parent.parent / "program" / "code" / "raindance_heightmap.h"

GRID_N = 257
STEP_M = 8.0          # 8m per cell (Tribes 1 native)
VERT_SCALE_M = 200.0  # meters of relief at raw=65535

img = Image.open(SRC)
assert img.size == (GRID_N, GRID_N), f"expected {GRID_N}x{GRID_N}, got {img.size}"
assert img.mode in ("I;16", "I"), f"expected 16-bit grayscale, got {img.mode}"

raw = np.array(img, dtype=np.float32)
heights_m = (raw / 65535.0) * VERT_SCALE_M
hmin = float(heights_m.min())
hmax = float(heights_m.max())
hmean = float(heights_m.mean())

print(f"loaded {SRC.name}: {raw.shape}, raw [{int(raw.min())}..{int(raw.max())}]")
print(f"heights_m: min={hmin:.3f} max={hmax:.3f} mean={hmean:.3f}")
print(f"world: {GRID_N - 1} * {STEP_M}m = {(GRID_N - 1) * STEP_M:.0f}m square")
print(f"writing header to {DST_HEADER}")

lines = []
lines.append("#ifndef RAINDANCE_HEIGHTMAP_H")
lines.append("#define RAINDANCE_HEIGHTMAP_H")
lines.append("")
lines.append("// Generated by assets/maps/raindance/build_heightmap.py")
lines.append("// Source: levizoesch/tribes.mapping (MIT) Raindance.png 257x257 16-bit grayscale")
lines.append(f"// Vertical scale: raw uint16 [0..65535] -> [0..{VERT_SCALE_M:.1f}]m")
lines.append("// Native Tribes 1 grid: 256+1 vertices, 8m spacing, 2048m square")
lines.append("")
lines.append(f"static const int RAINDANCE_SIZE = {GRID_N}; // 256+1")
lines.append(f"static const float RAINDANCE_HEIGHT_MIN = {hmin:.6f}f;")
lines.append(f"static const float RAINDANCE_HEIGHT_MAX = {hmax:.6f}f;")
lines.append("")
lines.append(f"static const float RAINDANCE_HEIGHTS[{GRID_N}][{GRID_N}] = {{")
for z in range(GRID_N):
    row_vals = ", ".join(f"{heights_m[z, x]:.4f}f" for x in range(GRID_N))
    comma = "," if z < GRID_N - 1 else ""
    lines.append(f"    {{{row_vals}}}{comma}")
lines.append("};")
lines.append("")
lines.append("#endif // RAINDANCE_HEIGHTMAP_H")

DST_HEADER.write_text("\n".join(lines))
sz = DST_HEADER.stat().st_size
print(f"wrote {DST_HEADER} ({sz} bytes, {sz/1024:.1f} KB)")
